from_latest_tag = false
ignore_merge_commits = false
tag_prefix = "v"
branch_whitelist = ["main"]

pre_bump_hooks = [
  "sed -i 's/^version = \"[0-9\\.]\\+\"/version = \"{{version}}\"/' Cargo.toml",
]
post_bump_hooks = ["git push", "git push origin {{version}}"]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "raifthenerd"
repository = "julia_docsets"
authors = [{ signature = "Seokjin Han", username = "raifthenerd" }]
